### ISSUE TITLE
Register clock.reset() on td.reset()

### ISSUE THREAD

**Issue by searls** [kuy/testdouble-timers#1]
Users should always be using td.reset() in a global afterEach hook, and there is an (undocumented) way to register additional behavior for the next call to td.reset(). 

whenever a user creates a timer, call `td.reset.onNextReset(clock.reset)`

Once implemented, you shouldn't need to tell your users about the separate reset() API 

You can see the function here https://github.com/testdouble/testdouble.js/blob/master/src/reset.coffee

**Comment by kuy** [comment]
Sweet! ✨ 
To ensure behaviors, I write a test before implementing.

**Comment by kuy** [comment]
Fixed at 595cea0eb18bb552e5b82457e50509a005808b63 and released [0.1.0](https://github.com/kuy/testdouble-timers/releases/tag/v0.1.0).
Thanks @searls !
