### ISSUE TITLE
Old peer dependency

### ISSUE THREAD

**Issue by bjarketrux** [kuy/testdouble-timers#3]
When using timers with a newer version of testdouble.js I get this warning:
```
warning "testdouble-timers@0.1.0" has incorrect peer dependency "testdouble@^1.4.2".
```

**Comment by kuy** [comment]
@bjarketrux Just released 0.1.1 which resolves peer dependency problem by bumping up testdouble.js version to 3.x. I hope this release addresses your issue. If not (unfortunately), please let me know or send PRs. Thanks for reporting!
